# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 12:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Market')),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ask', models.DecimalField(decimal_places=8, max_digits=16)),
                ('bid', models.DecimalField(decimal_places=8, max_digits=16)),
                ('volume', models.DecimalField(decimal_places=8, max_digits=16)),
                ('status', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading.Market')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.AlterUniqueTogether(
            name='price',
            unique_together=set([('market', 'created_at')]),
        ),
    ]
